server:
  port: 8080

# 配置真实数据源
spring:
  shardingsphere:
    datasource:
      ds0:
        type: org.apache.commons.dbcp2.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds0
        username: root
        password: root
      ds1:
        type: org.apache.commons.dbcp2.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds0
        username: root
        password: root
    rules:
      sharding:
        table:
          t_order:
            actual-data-nodes: ds$->{0..1}.t_order$->{0..1}
            database-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: database_inline
            table-strategy:
              standard:
                sharding-column: order_id
                sharding-algorithm-name: table_inline
        sharding-algorithms:
          database_inline:
            type: INLINE
            props:
              algorithm-expression: ds_${user_id % 2}
          table_inline:
            type: INLINE
            props:
              algorithm-expression: t_order_${order_id % 2}