server:
  port: 18090 #服务端口号


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:18080/eureka #eureka服务端注册地址
    registry-fetch-interval-seconds: 5  #指从eureka服务器获取注册表信息的频率（s）
    fetch-registry: true   #是否从eureka获取注册信息
    register-with-eureka: true  #是否注册到 eureka
  instance:
    health-check-url-path: /health #健康检查页面的URL，相对路径，默认使用HTTP访问
    status-page-url-path: /info   #状态页面的URL，相对路径，默认使用 HTTP 访问
    prefer-ip-address: true  # 使用ip注册
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}）


spring:
  application:
    name: customer-microservice #服务实例名称


logging:
  config: classpath:logback/logback.xml   #logback日志配置