server:
  port: 8080

spring:
  redis:
    database: 0 #数据库索引
    host: 192.168.44.128 #redis地址
    password: 123456 #密码
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 8 #最大空闲
        min-idle: 0 #最小空闲
    timeout: 10000 #连接超时时间，默认是20000毫秒
